name: CI/CD stepSOLAR Docs
on:
  push:
    branches:
      - main  # Spustí sa pri každom pushi do hlavnej vetvy

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-minify-plugin

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force